/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iyich_wallet_lib_jni_SecLinkJni */

#ifndef _Included_com_iyich_wallet_lib_jni_SecLinkJni
#define _Included_com_iyich_wallet_lib_jni_SecLinkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iyich_wallet_lib_jni_SecLinkJni
 * Method:    veritySession
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iyich_wallet_lib_jni_SecLinkJni_veritySession
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_iyich_wallet_lib_jni_FastModeJNI
 * Method:    sendData
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iyich_wallet_lib_jni_SecLinkJni_sendData
        (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_iyich_wallet_lib_jni_FastModeJNI
 * Method:    onReceive
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iyich_wallet_lib_jni_SecLinkJni_onReceive
        (JNIEnv *, jobject, jbyteArray, jint);


#ifdef __cplusplus
}
#endif
#endif
